### ISSUE TITLE
PERMISSION_DENIED  on vote

### ISSUE THREAD

**Issue by ak4t0sh** [dvdcastro/moodle-mod_livepoll#3]
I followed your configuration instructions to setup Firebase and add an instance in a Moodle (3.6.2+ (Build: 20190215)) course but I have the following error when I try vote :

```
moodle-core-event: Global event published: FORM_ERROR yui_combo.php:5828:31
moodle-core-event: Global event published: BLOCK_CONTENT_UPDATED yui_combo.php:5828:31
livepoll UI has been updated. first.js:49:143
[2019-02-18T17:19:54.685Z]  @firebase/database: FIREBASE WARNING: set at /polls/cbf2985f581c97bcfe62df133f4cde4fc84e4445/votes/50c66fff4b5e78cc973c9a365dbe7f5fc1fe73f6 failed: permission_denied index.esm.js:74:12
Error: PERMISSION_DENIED: Permission denied
```

Is there any undocumented configuration to do ?

**Comment by dvdcastro** [comment]
I realized I had already added the step, Did you set authentication as anonymous?

https://youtu.be/ApG8L2RKrSI?t=249

**Comment by ak4t0sh** [comment]
yes I already enabled anonymous sign in and when I load a poll instance I can see logs in `firebase console > authentication` the error occur when I click an option to vote.
I also tried : 
* adding my domain in `firebase console > authentication > sign in methods`
* creating a new project and select public in database rules

Same result >_<   Next step : new google and firebase account ? xD

Note: my moodle wwwroot is a subdirectory (https://example.com/moodle) does firebase javascript correctly handle this case?

**Comment by dvdcastro** [comment]
I've added a new commit a46f3f4 with enhancements to firebase authentication, Can you try again and let me know what comes out in the console?

**Comment by ak4t0sh** [comment]
Tried using : Firefox 65.0 (Debian sid 64-bits and Windows 10 64-bits) Chromium 72.0.3626.109 on Debian(sid 64-bit), Chrome 72.0.3626.109 on Windows 10.  
The following log appear when I load the activity for the first time in a browser session (reproducted each time I open a new private windows).  
It does not appear when I reload the page even with cache disabled.  
  
`User has signed out from firebase.  first.js:49:143
	a.methodFactory/< https://xxxxxx/moodle/lib/requirejs.php/1550642184/core/first.js:49:143
	f/< https://xxxxxx/moodle-master/lib/requirejs.php/1550642184/mod_livepoll/livepoll-lazy.js:1:942
	nr</t.prototype.next/< https://www.gstatic.com/firebasejs/5.2.0/firebase-app.js:1:28939
	nr</t.prototype.sendOne/< https://www.gstatic.com/firebasejs/5.2.0/firebase-app.js:1:30236`
  
Unrelated (I think) note: when I want to add an app on Firebase console it give me https://www.gstatic.com/firebasejs/5.8.3/firebase.js URL but you are using 5.2.0.

**Comment by ak4t0sh** [comment]
Tested on an other Moodle with wwwroot at / => same behavior

**Comment by dvdcastro** [comment]
Okay, I'm getting that same error but the poll is working. Is it working for you?

Just added 58b2b6b to make that user log out message output not as an error.

**Comment by ak4t0sh** [comment]
Test with chromium :  
`User has signed out from firebase.
first.js:49 User has signed in to firebase.
first.js:49 livepoll UI has been updated.
index.esm.js:641 Uncaught (in promise) Error: permission_denied at /polls/fd4848a7e83e639de3dcf74ba028c97a20240b8b/votes/741660acc6062a61ba954de9d60a7fb34c67ceff: Client doesn't have permission to access the desired data.
    at index.esm.js:641
    at onComplete (index.esm.js:9108)
    at Object.onComplete (index.esm.js:12675)
    at index.esm.js:11791
    at n.onDataMessage_ (index.esm.js:12046)
    at t.onDataMessage_ (index.esm.js:11331)
    at t.onPrimaryMessageReceived_ (index.esm.js:11325)
    at t.onMessage (index.esm.js:11226)
    at t.appendFrame_ (index.esm.js:10831)
    at t.handleIncomingFrame (index.esm.js:10881)
(anonymous) @ index.esm.js:641
onComplete @ index.esm.js:9108
(anonymous) @ index.esm.js:12675
(anonymous) @ index.esm.js:11791
n.onDataMessage_ @ index.esm.js:12046
t.onDataMessage_ @ index.esm.js:11331
t.onPrimaryMessageReceived_ @ index.esm.js:11325
(anonymous) @ index.esm.js:11226
t.appendFrame_ @ index.esm.js:10831
t.handleIncomingFrame @ index.esm.js:10881
mySock.onmessage @ index.esm.js:10778
Promise.then (async)
(anonymous) @ livepoll-lazy.js:1
dispatch @ jquery-3.2.1.min.js:1
q.handle @ jquery-3.2.1.min.js:1`
  
With Firefox:  
`User has signed out from firebase.
first.js:49 User has signed in to firebase.
first.js:49 livepoll UI has been updated.`

=> no error on click but does not work

If it can help you to see if there is a misconfiguration in my firebase projects, I added you as owner on them.

**Comment by dvdcastro** [comment]
What does the rules for database tab say?
![firebase-rules](https://user-images.githubusercontent.com/1523388/53123057-32dec380-3526-11e9-8783-66626742e07a.png)
I don't remember if I edited this part..

**Comment by dvdcastro** [comment]
If that doesn't work, Could you invite my gmail account? davidcastro00

**Comment by ak4t0sh** [comment]
I do not know I never used Firebase before so I followed your instructions and it did not mention accessing database section ^^.  
From your screenshot I see you have selected "Realtime Database".  
By default my Firebase console displayed "Cloud Firestore" databases, so I let it selected and tried changing rules on this one. It did not change "Realtime Database" configuration.  
Which value should be there ?

**Comment by dvdcastro** [comment]
This is my fault, sorry for your time lost.

I've added better instructions d38a308 , at the time I used firebase when I created this project, the steps weren't that long.

**Comment by ak4t0sh** [comment]
I have created a new project follow your enhanced instructions and......it works :) :+1:   
Do not worry I did not waste my time. That's what tests and reviews are for ;)

![image](https://user-images.githubusercontent.com/2222386/53148941-87c51d00-35ac-11e9-9ff0-8759cc5a4e97.png)
