### ISSUE TITLE
Privacy API : external location

### ISSUE THREAD

**Issue by ak4t0sh** [dvdcastro/moodle-mod_livepoll#5]
As you store answer in a way that allow to identify the user (his id) I think you should implements :
https://docs.moodle.org/dev/Privacy_API#Indicating_that_you_export_data_to_an_external_location

please note - this is not a blocker for approval in the plugins db but would be nice to add at some point.

**Comment by ak4t0sh** [comment]
Sorry my message was not really clear.
As you hash it you do not really store the user id. But you store the selected option.
I think that is this data you should declare :)

**Comment by dvdcastro** [comment]
Does this look better? 6eadf39

**Comment by ak4t0sh** [comment]
I'm not a privacy expert but it seems good to me :)
